name: Execute tests from automation framework
on: [workflow_dispatch]  
jobs:
  Execute-tests:
    runs-on: ubuntu-latest  
    steps:
    - name: Docker pull  
      run: docker pull coherentsolutions/rest-training:2.0 
    - name: Deploy API image to Github hosted runner
      run: docker run -d -p 49000:8082 coherentsolutions/rest-training:2.0   

    # Install .NET SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Check out your code from git repository 
    - name: Checkout code
      uses: actions/checkout@v4    
      
    # Build your framework (including restore of dependencies: NuGet packages etc. )   
    - name: Build
      run: dotnet build
      
    # Execute tests against deployed application
    - name: Execute tests
      run: dotnet test --no-restore --verbosity normal

    # Publish Allure results via:https://allurereport.org/docs/integrations-github/   
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: test_results
        path: test_results

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: test_results
        allure_history: allure-history
        allure_results: build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: test_results
        publish_dir: allure-history


